spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./devdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update

campaignlink: "https://mailcampaignn.herokuapp.com/campaignlink/"